const values = [
  'Pizza ipsum dolor amet steak pepperoni white pizza pizza roll, lasagna pie fresh tomatoes. Personal pesto mozzarella pineapple. Ricotta chicken pepperoni red onions sausage deep crust ham mushrooms, bbq rib onions bacon thin crust. Philly chicken meatball pesto beef chicken chicken and bacon. Stuffed crust sausage extra cheese black olives banana peppers white pizza mozzarella pork pesto mayo string cheese. Chicken personal black olives red onions broccoli garlic parmesan sausage. Sausage garlic stuffed chicken wing pie.',

  'Ranch fresh tomatoes Chicago style philly steak, broccoli extra sauce chicken chicken and bacon spinach garlic white pizza. Pork white pizza meatball, thin crust pizza roll chicken wing banana peppers Chicago style. Garlic thin crust onions pork. Personal Chicago style fresh tomatoes philly steak, ham bianca pork parmesan steak string cheese buffalo sauce pepperoni sausage pepperoni. String cheese bbq sauce pizza garlic parmesan, red onions bacon white pizza anchovies onions sauteed onions sausage spinach philly steak banana peppers.',

  'Pie thin crust white garlic green bell peppers bbq rib pan. Pork large bacon & tomato bbq sauteed onions extra sauce pizza roll meatball onions buffalo sauce bacon garlic sauce thin crust philly chicken red onions. White pizza bacon & tomato green bell peppers bacon steak deep crust ranch string cheese beef mushrooms ricotta melted cheese mayo. White pizza mushrooms onions, steak ricotta chicken Chicago style.',

  'Pepperoni philly steak meatball pizza roll buffalo sauce mayo platter meat lovers pizza ham. Bacon bianca chicken and bacon peppers pan. Stuffed crust deep crust bacon pork peppers party. Ham ricotta mushrooms stuffed crust chicken and bacon. Personal lasagna stuffed crust, thin crust white pizza bacon & tomato extra cheese black olives green bell peppers garlic parmesan mozzarella pizza roll.',

  'Sausage stuffed red onions, bacon hand tossed buffalo sauce chicken wing platter broccoli pepperoni pan NY style bbq rib. Peppers pesto NY style pie pineapple ranch sausage garlic parmesan steak bbq extra sauce string cheese onions stuffed. Pepperoni bbq rib bacon, steak large banana peppers meatball personal pizza roll NY style parmesan mozzarella onions. White garlic garlic sauce black olives, ham extra cheese pepperoni red onions pepperoni ricotta bacon & tomato chicken and bacon pizza platter chicken pineapple. Party meatball beef, bbq sauce fresh tomatoes personal bacon pesto anchovies white garlic hawaiian green bell peppers bbq rib. Banana peppers melted cheese bacon thin crust mushrooms party.',

  'Pan meatball garlic, white garlic black olives chicken and bacon meat lovers parmesan marinara spinach pepperoni steak Chicago style anchovies string cheese. Red onions pan lasagna NY style, buffalo sauce hawaiian Chicago style green bell peppers mozzarella thin crust. Philly steak chicken wing onions bacon & tomato. Melted cheese large buffalo sauce mayo white pizza white garlic stuffed crust. Pizza roll marinara banana peppers bbq sauce garlic deep crust onions, pork bbq party broccoli steak thin crust.',

  'Hawaiian sauteed onions pie chicken thin crust bianca peppers melted cheese red onions deep crust garlic stuffed pepperoni personal fresh tomatoes. Chicken wing melted cheese fresh tomatoes, broccoli meat lovers lasagna string cheese peppers mayo steak white garlic sauteed onions party pan pizza roll. Pineapple pan anchovies, sausage beef spinach bbq sauce meatball garlic sauce philly chicken lasagna marinara. Thin crust chicken bbq rib bbq hand tossed parmesan burnt mouth NY style chicken wing extra sauce lasagna stuffed. Sausage pork garlic burnt mouth bacon & tomato mushrooms black olives chicken and bacon garlic sauce meatball ranch.',

  'Philly steak red onions fresh tomatoes, green bell peppers large extra cheese personal lasagna. Pan bianca green bell peppers fresh tomatoes. Buffalo sauce chicken wing mushrooms beef. Melted cheese garlic parmesan thin crust pork, string cheese marinara extra cheese hand tossed garlic sauce pepperoni onions buffalo sauce meat lovers fresh tomatoes mayo.',
];

module.exports = values;
